DROP TABLE IF EXISTS owners CASCADE ;
DROP TABLE IF EXISTS solutions CASCADE ;
DROP TABLE IF EXISTS track_times CASCADE ;

CREATE TABLE IF NOT EXISTS owners
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(30)                             NOT NULL,
    email VARCHAR(254)                            NOT NULL,
    CONSTRAINT pk_owners PRIMARY KEY (id),
    CONSTRAINT uq_owner_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS solutions
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    version  VARCHAR(15)                             NOT NULL,
    owner_id BIGINT                                  REFERENCES owners (id) ON DELETE SET NULL,
    CONSTRAINT pk_solutions PRIMARY KEY (id),
    CONSTRAINT uq_solutions_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS track_times
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR,
    is_async BOOLEAN,
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    execution_duration BIGINT
);